feat: QOL fixes
talo/rush-py-legacy pull request #22
Opened 2024-01-22 07:18 UTC by ryanswrt

This PR fixes some bugs around fetching and retrying.

It also adds a method for rendering 3d molecules in the notebook

2024-01-23 15:35 UTC, seankhl requested changes
There's some more stuff to clean up but I think I addressed everything worth addressing right now.

Note that I didn't look at the notebooks under Tutorials at all or try to run them, but I did check the README which is of course generated from the index notebook.

2024-01-23 15:35 UTC, seankhl commented on tengu/provider.py
> +                                    )
Woudln't `remote_arg.source or self.source` always evaluate to `True` since we're in this if branch? My python understanding by memory could be off here. Do you mean `remote_arg.source if remote_arg.source else self.source`?

2024-01-23 15:35 UTC, seankhl commented on tengu/provider.py
> +                            raise e
Is the actual exception not generic enough that you can't handle the specific "not found" exception and then the others as separate `except` cases?

2024-01-23 15:35 UTC, seankhl commented on tengu/provider.py
> +        # always request a bit of space because the a run will always create files
```suggestion
        # always request a bit of space because a run will always create files
```

2024-01-23 15:35 UTC, seankhl commented on nbs/sidebar.yml
>        - section: api
```suggestion
      - section: API
```

2024-01-23 15:35 UTC, seankhl commented on nbs/sidebar.yml
>        - section: api
Is there a way to make this section not have a drop-down since there are no items inside it? The html looks a little weird. Not a big deal

2024-01-23 15:35 UTC, seankhl commented on pyproject.toml
> +documentation = "https://talo.github.io/tengu-py/"
```suggestion
documentation = "https://talo.github.io/tengu-py"
```

2024-01-23 15:35 UTC, seankhl commented on pyproject.toml
> +homepage = "https://rush.qdx/co"
```suggestion
homepage = "https://rush.qdx.co"
```

2024-01-23 15:35 UTC, seankhl commented on README.md
>  WORK_DIR = Path.home() / "qdx" / "tengu-py-demo"
```suggestion
# Make sure you create a unique set of tags for each run.
# Good practice is to have at least each of the experiment name and system name as a tag.
EXPERIMENT = "tengu-py-v2-tutorial"
SYSTEM = "cdk2"
TAGS = ["qdx", EXPERIMENT, SYSTEM]
WORK_DIR = Path.home() / "qdx" / EXPERIMENT
```

2024-01-24 01:48 UTC, ryanswrt commented on tengu/provider.py
> +                                    )
In python `False or 2` evaluates to 2.

2024-01-24 01:50 UTC, ryanswrt commented on tengu/provider.py
> +                            raise e
Nope we just get GraphQLError back from the client. I could filter it for this case, but I think this is fine

2024-01-24 01:52 UTC, ryanswrt commented on nbs/sidebar.yml
>        - section: api
This file is autogenerated by nbdev, can't really edit it permanently

2024-01-24 02:03 UTC, ryanswrt commented on README.md
>  WORK_DIR = Path.home() / "qdx" / "tengu-py-demo"
Will address this in a future PR

2024-01-24 02:03 UTC, merged