fix: blocking client nbs
talo/rush-py-legacy pull request #74
Opened 2024-03-20 09:00 UTC by ryanswrt

Contains #72 

This pr adds a blocking provider, allowing users to write code without calling await everywhere and using an asycio runtime.

It also adds and implements support for the RUSH_RESTORE_BY_DEFAULT env var, allowing us to easily test restored + unrestored workflows in CI (and cleans up the broken hideline stuff we tried in the quickstarts)

It also makes type inference a bit better in pyright by not relying on exec.

2024-03-21 09:19 UTC, seankhl requested changes
- We should be using `download().read_text()`, not `download().open().read()`, since the formaer automatically closes the file after reading and is simpler and clearer.
  - `(conformer,) = ` should be rewritten as `conformer, = ` without parens. Parens should be omitted for any destructuring assignments.

There are a few other notebook changes, I'm going to go through them now, so another review will come.

2024-03-21 09:19 UTC, seankhl commented on README.md
> +This document will walk through executing jobs on the Rush platform, by
```suggestion
This document will walk through executing jobs on the Rush platform by
```

2024-03-21 09:19 UTC, seankhl commented on rush/legacy_types.py
> +from typing import Any, Union
We should conditionally import `Union` too

2024-03-21 09:19 UTC, seankhl commented on flake.nix
> +    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
Should we only use unstable for 3.12?

2024-03-21 09:19 UTC, seankhl commented on flake.nix
> +        };
I feel like 3.11 should be the default and 3.12 can be its own named target.

2024-03-21 09:22 UTC, seankhl commented on flake.nix
> +        };
Hmm though running the notebooks on 3.12 will result in nicer types in the output.

2024-03-21 09:48 UTC, ryanswrt commented on flake.nix
> +        };
Yep that's what I thought

2024-03-21 10:10 UTC, ryanswrt commented on flake.nix
> +    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
Not possible at the moment to have 2 different versions of nixpkgs passed to poetry

2024-03-21 10:16 UTC, seankhl submitted a review, later dismissed
- index.py section 2.2: do we want the text "Blocking get" to appear in the output?
  - Likewise with `read_text()` we should use `write_text()` too instead of printing to an opened file or other such things
  - See the latest commit for more expected changes that should be applied similarly to the index, explainer, and tutorials

2024-03-21 10:16 UTC, seankhl commented on rush/provider.py
> +            print("Blocking get")
Delete this line?

2024-03-21 10:25 UTC, seankhl commented
One last thing: it would be good to homogeneize all the tag strings, like "{nb_name}_quickstart". Right now they're not super uniform.

2024-03-22 09:57 UTC, seankhl approved these changes

2024-03-22 09:57 UTC, merged